# _config.yml

title: "中文标题"
description: "last name ever, first name greatest"
# remote_theme: "wowthemesnet/jekyll-theme-memoirs"
remote_theme: "wowthemesnet/mediumish-theme-jekyll"
comments: true
author: noMoon

lazyimages: "enabled"

lang: zh