# _config.yml

title: "中文标题 title in config"
description: "last name ever, first name greatest"
# remote_theme: "wowthemesnet/jekyll-theme-memoirs"
remote_theme: "mmistakes/jekyll-theme-basically-basic"
comments: true
author: noMoon
logo: "assets/logo.png"
lazyimages: "enabled"

lang: zh